name: Simple secrets example
on:
  push:
    branches:
      - main
jobs:
  print_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print the secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "The secret key is $MY_SECRET"